name: text_comparison_score_codespark
description: "The TextComparisonScore package is a straightforward and efficient tool for comparing two strings and calculating their similarity score using the Levenshtein distance algorithm."
version: 0.0.2
homepage: https://github.com/Katayath-Sai-Kiran/text_comparison_score_codespark

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">= 1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

screenshots:

  - description: 'Demonstrates how to use the text_comparison_score_codespark package to compare two text strings and calculate their similarity score.'
    path: assets/sample.png
    width: 300

topics:

  - textcomparison
  - compare
  - score
  - levenshteindistance